

export const data = {
    redirection: '',
    darkmode: false,
    actualSort: "NO_SORT",
	filter: {
		minPrice: 0,
		maxPrice: 80000,
		minNotation: 0,
		maxNotation: 5
	},
    categories: [
        "standard-balls",
        "special-balls",
        "healing",
        "status-cures",
        "revival",
        "pp-recovery",
        "vitamins",
        "stat-boosts",
        "spelunking",
        "flutes",
        "collectibles",
        "evolution",
        "loot",
        "dex-completion",
        "mulch",
        "species-specific",
        "all-mail",
        "medicine",
        "picky-healing",
        "baking-only",
        "effort-drop",
        "type-protection",
        "in-a-pinch",
        "other",
        "held-items",
        "effort-training",
        "training",
        "choice",
        "type-enhancement",
        "scarves",
        "bad-held-items",
        "plates",
        "all-machines",
        "gameplay",
        "unused",
        "plot-advancement",
        "event-items",
        "apricorn-balls",
        "apricorn-box",
        "data-cards",
        "jewels",
        "miracle-shooter",
        "mega-stones",
        "z-crystals",
        "memories"
    ],
};
