type Comment {
    "Identifiant unique du commentaire"
    c_uid: ID!

    "Identifiant unique de l'auteur"
    author: ID!

    "Date de publication"
    date: String!

    "Contenu du commentaire"
    message: String!

    "Note du produit"
    note: Float!
}