type Mutation {
    "Ajouter un produit à la vente"
    createProduct(
        auth: AuthInfo!,
        seller: String!,
        title: String!,
        stock: Int!,
        description: String!,
        category: String!,
        price: Float!,
    ) : String

    "Ajouter une image à un produit"
    addImageToProduct(
        auth: AuthInfo!,
        p_uid: ID!,
        image: String!
    ) : String

    "Mettre a jour les informations d'un produit"
    updateProduct(
        auth: AuthInfo!,
        p_uid: ID!,
        title: String!,
        stock: String!,
        description: String!,
        category: String!,
        price: Float!,
    ) : String

    "Ajouter une catégorie"
    pushCategory(
        auth: AuthInfo!,
        category: String!
    ) : String

    "Traiter une commande"
    processOrder(
        auth: AuthInfo!,
        items: [Order!]!
    ) : String

    "Ajouter un commentaire sur un produit"
    createComment(
        auth: AuthInfo!,
        p_uid: ID!,
        message: String!,
        note: Float!
    ) : String

    "Mettre a jour un commentaire"
    updateComment(
        auth: AuthInfo!,
        c_uid: ID!,
        message: String!,
        note: String!,
    ) : String

    "Supprimer un commentaire"
    deleteComment(
        auth: AuthInfo!,
        p_uid: ID!,
        c_uid: ID!,
    ): Boolean

    "Créer un compte"
    createUser(
        nickname: String!,
        email: String!,
        password: String!
    ) : String

    "Mettre a jour les informations d'un utilisateur"
    updateUser(
        auth: AuthInfo!,
        email: String!,
        nickname: String!,
    ) : String

    "Ajouter un produit à la wishlist"
    addToWishlist(
        auth: AuthInfo!
        product: ID!
    ) : String

    "Retirer un produit de la wishlist"
    removeFromWishlist(
        auth: AuthInfo!
        product: ID!
    ) : String
}

input Order {
    "Identifiant unique du produit a acheter"
    p_uid: ID!,

    "Quantité du produit à acheter"
    quantity: Int!
}