type Mutation {
    "PRODUITS"
    createProduct(
        uid: String,
        seller: String, 
        title: String, 
        stock: Int, 
        description: String, 
        category: String, 
        price: Float,   
    ) : String "retourne p_uid pour l'upload d'images."

    updateProduct(
        uid: String,
        p_uid: String,
        title: String,
        stock: String,
        description: String,
        category: String,
        price: Float,
    ) : String

    processOrder(
        uid: String,
        items: [Order]
    ) : String

    "COMMENTAIRES"
    createComment(
        uid: String,
        p_uid: String,
        message: String,
        note: Float
    ) : String

    updateComment(
        uid: String,
        c_uid: String,
        message: String,
        note: String,
    ) : String

    deleteComment(
        uid: String,
        p_uid: String,
        c_uid: String,
    ): Boolean

    "UTILISATEURS"
    createUser(
        nickname: String,
        email: String,
    ) : String

    updateUser(
        uid: String,
        email: String,
        nickname: String,
    ) : String
}

input Order {
    p_uid: String!,
    quantity: Int!
}