type Mutation {
    createProduct(
        seller: String, 
        title: String, 
        stock: Int, 
        description: String, 
        category: String, 
        price: Float,   
    ) : Product
}