type Product {
    p_uid: ID!
    seller: String!
    title: String!
    stock: Int!
    description: String!
    images: [String!]!
    category: String!
    comments: [String!]!
    notation: Float!
    price: Float!
    sales: Int!
    views: Int!
}

type SearchResult {
    meta: SearchResultMetadata
    results: [Product]
}

type SearchResultMetadata {
    totalCount: Int!
    totalPages: Int!
}
