type Query {
    getProduct(p_uid: ID): Product
    getAllProducts: [Product]
    searchProduct(searchString: String, limit: Int, offset: Int): SearchResult
    top(categorie: String, champ: String) : [Product]

    "FONCTIONS USER"
    connect(nickname: String, hash: String) : AuthData
    disconnect(auth: AuthInfo) : String
    isConnected(auth: AuthInfo) : Boolean
    getUser(uid: String) : User
    getNickname(uid: String) : String
    getHistory(uid: String) : [HistoryElement]
    getNotation(target_uid: String) : Float

    "COMMENTAIRES"
    getComment(c_uid: String) : Comment
    getCommentsOfProduct(p_uid: String) : [Comment]
}

type AuthData {
    uid: String
    token: String
}

input AuthInfo {
    uid: String
    token: String
}