type Query {
    getProduct(p_uid: ID): Product
    getAllProducts: [Product]
    searchProduct(searchString: String, limit: Int, offset: Int): SearchResult
    top(categorie: String, champ: String) : [Product]

    "FONCTIONS USER"
    user(uid: String) : User
    users: [User]

    "FONCTIONS AUTH"
    uid(hash: String) : String
}