type HistoryElement {
    type: HistoryElementType!
    product: String!
}

enum HistoryElementType {
    BUY,
    SELL
}

type User {
    uid: String!
    hash: String!
    nickname: String!
    email: String!
    wishlist: [String!]!
    totalSales: Int!
    notation: Float!
    history: [HistoryElement!]!
}
